# Change these first
owner: bigbang1112 # Your GitHub organization or username, where this repository lives
repo: bigbang1112cz-uptime # The name of this repository

sites:
  - name: bigbang1112.cz
    url: https://bigbang1112.cz
  - name: v2.bigbang1112.cz
    url: https://v2.bigbang1112.cz
  - name: gbx.bigbang1112.cz (Gbx Web Tools)
    url: https://gbx.bigbang1112.cz
  - name: wr.bigbang1112.cz (TMWR / World Record Report)
    url: https://wr.bigbang1112.cz
  - name: tmtr.bigbang1112.cz
    url: https://tmtr.bigbang1112.cz
  - name: purge2.bigbang1112.cz (TMUF Purge 2)
    url: https://purge2.bigbang1112.cz
  - name: antislowmo.bigbang1112.cz (TMUF Purge 1)
    url: https://antislowmo.bigbang1112.cz
  - name: antislowmo.bigbang1112.cz (TMUF Purge 1, Dortmund)
    url: https://dortmund.antislowmo.bigbang1112.cz
    
assignees: # Users to assign downtime issues (optional)
  - BigBang1112

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.bigbang1112.cz
  #baseUrl: /gbx-tools-uptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: status.bigbang1112.cz
  introTitle: "**BigBang1112.cz** status page"
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
